07-07-2015 11:16:36 ERROR[TestDriver]: This is sample error message
07-07-2015 11:28:00 ERROR[TestDriver]: This is sample error message
07-07-2015 11:32:19 ERROR[TestDriver]: This is sample error message
07-07-2015 11:33:48 ERROR[TestDriver]: This is sample error message
07-07-2015 11:39:12 ERROR[TestDriver]: This is sample error message
07-07-2015 11:41:50 ERROR[TestDriver]: This is sample error message
07-07-2015 11:50:33 ERROR[TestDriver]: This is sample error message
07-07-2015 11:53:10 ERROR[TestDriver]: This is sample error message
07-07-2015 11:54:00 ERROR[TestDriver]: This is sample error message
07-07-2015 12:21:18 ERROR[TestDriver]: This is sample error message
07-07-2015 12:21:18 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:21:18 ERROR[TestDriver]: This is sample error message
07-07-2015 12:21:18 ERROR[TestDriver]: This is sample error message
07-07-2015 12:24:36 ERROR[TestDriver]: This is sample error message
07-07-2015 12:24:36 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:24:36 ERROR[TestDriver]: This is sample error message
07-07-2015 12:24:36 ERROR[TestDriver]: This is sample error message
07-07-2015 12:29:02 ERROR[TestDriver]: This is sample error message
07-07-2015 12:29:02 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:29:02 ERROR[TestDriver]: This is sample error message
07-07-2015 12:29:02 ERROR[TestDriver]: This is sample error message
07-07-2015 12:29:24 ERROR[TestDriver]: This is sample error message
07-07-2015 12:30:02 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:30:10 ERROR[TestDriver]: This is sample error message
07-07-2015 12:30:10 ERROR[TestDriver]: This is sample error message
07-07-2015 12:38:52 ERROR[TestDriver]: This is sample error message
07-07-2015 12:38:53 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:38:53 ERROR[TestDriver]: This is sample error message
07-07-2015 12:38:53 ERROR[TestDriver]: This is sample error message
07-07-2015 12:39:51 ERROR[TestDriver]: This is sample error message
07-07-2015 12:39:51 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:39:51 ERROR[TestDriver]: This is sample error message
07-07-2015 12:39:51 ERROR[TestDriver]: This is sample error message
07-07-2015 12:48:37 ERROR[TestDriver]: This is sample error message
07-07-2015 12:48:37 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:48:37 ERROR[TestDriver]: This is sample error message
07-07-2015 12:48:37 ERROR[TestDriver]: This is sample error message
07-07-2015 12:50:29 ERROR[TestDriver]: This is sample error message
07-07-2015 12:50:29 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:50:29 ERROR[TestDriver]: This is sample error message
07-07-2015 12:50:29 ERROR[TestDriver]: This is sample error message
07-07-2015 12:55:26 ERROR[TestDriver]: This is sample error message
07-07-2015 12:55:26 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:55:26 ERROR[TestDriver]: This is sample error message
07-07-2015 12:55:26 ERROR[TestDriver]: This is sample error message
07-07-2015 12:56:23 ERROR[TestDriver]: This is sample error message
07-07-2015 12:56:23 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:56:23 ERROR[TestDriver]: This is sample error message
07-07-2015 12:56:23 ERROR[TestDriver]: This is sample error message
07-07-2015 12:57:15 ERROR[TestDriver]: This is sample error message
07-07-2015 12:57:15 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 12:57:15 ERROR[TestDriver]: This is sample error message
07-07-2015 12:57:15 ERROR[TestDriver]: This is sample error message
07-07-2015 13:26:58 ERROR[TestDriver]: This is sample error message
07-07-2015 13:26:58 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 13:26:58 ERROR[TestDriver]: This is sample error message
07-07-2015 13:26:58 ERROR[TestDriver]: This is sample error message
07-07-2015 13:28:35 ERROR[TestDriver]: This is sample error message
07-07-2015 13:28:35 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 13:28:35 ERROR[TestDriver]: This is sample error message
07-07-2015 13:28:35 ERROR[TestDriver]: This is sample error message
07-07-2015 13:42:58 ERROR[TestDriver]: This is sample error message
07-07-2015 13:42:58 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 13:42:58 ERROR[TestDriver]: This is sample error message
07-07-2015 13:42:58 ERROR[TestDriver]: This is sample error message
07-07-2015 13:46:39 ERROR[TestDriver]: This is sample error message
07-07-2015 13:46:55 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 13:46:55 ERROR[TestDriver]: This is sample error message
07-07-2015 13:46:55 ERROR[TestDriver]: This is sample error message
07-07-2015 15:37:57 ERROR[TestDriver]: This is sample error message
07-07-2015 15:37:57 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 15:37:57 ERROR[TestDriver]: This is sample error message
07-07-2015 15:37:57 ERROR[TestDriver]: This is sample error message
07-07-2015 15:39:41 ERROR[TestDriver]: This is sample error message
07-07-2015 15:39:41 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 15:39:41 ERROR[TestDriver]: This is sample error message
07-07-2015 15:39:41 ERROR[TestDriver]: This is sample error message
07-07-2015 15:46:14 ERROR[TestDriver]: This is sample error message
07-07-2015 15:46:15 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:68)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 15:46:15 ERROR[TestDriver]: This is sample error message
07-07-2015 15:46:15 ERROR[TestDriver]: This is sample error message
07-07-2015 15:46:59 ERROR[TestDriver]: This is sample error message
07-07-2015 15:54:04 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:71)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 15:54:04 ERROR[TestDriver]: This is sample error message
07-07-2015 15:54:04 ERROR[TestDriver]: This is sample error message
07-07-2015 15:54:23 ERROR[TestDriver]: This is sample error message
07-07-2015 15:55:08 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:71)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 15:55:08 ERROR[TestDriver]: This is sample error message
07-07-2015 15:55:08 ERROR[TestDriver]: This is sample error message
07-07-2015 16:00:56 ERROR[TestDriver]: This is sample error message
07-07-2015 16:00:57 ERROR[TestDriver]: fnALMUpdate--------------Failed
java.lang.Exception: Error: No ALM Connection is open. Please call openConnection() method to open an ALM connection
	at com.homedepot.renowalk.UtilManager.ALMUtil.updateTestCaseStatusToALM(ALMUtil.java:71)
	at com.homedepot.renowalk.ReportManager.Reporter.fnALMUpdate(Reporter.java:540)
	at com.homedepot.renowalk.ReportManager.Reporter.repGenerateResult(Reporter.java:502)
	at com.homedepot.renowalk.TestDriver.run(TestDriver.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
07-07-2015 16:00:57 ERROR[TestDriver]: This is sample error message
07-07-2015 16:00:57 ERROR[TestDriver]: This is sample error message
07-07-2015 16:01:29 ERROR[TestDriver]: This is sample error message
07-07-2015 16:01:37 ERROR[TestDriver]: This is sample error message
07-07-2015 16:01:37 ERROR[TestDriver]: This is sample error message
07-07-2015 16:05:08 ERROR[TestDriver]: This is sample error message
07-07-2015 16:05:16 ERROR[TestDriver]: This is sample error message
07-07-2015 16:05:16 ERROR[TestDriver]: This is sample error message
07-07-2015 16:08:06 ERROR[TestDriver]: This is sample error message
07-07-2015 16:08:13 ERROR[TestDriver]: This is sample error message
07-07-2015 16:08:13 ERROR[TestDriver]: This is sample error message
07-07-2015 16:09:06 ERROR[TestDriver]: This is sample error message
07-07-2015 16:09:14 ERROR[TestDriver]: This is sample error message
07-07-2015 16:09:14 ERROR[TestDriver]: This is sample error message
07-07-2015 16:11:04 ERROR[TestDriver]: This is sample error message
07-07-2015 16:11:11 ERROR[TestDriver]: This is sample error message
07-07-2015 16:11:11 ERROR[TestDriver]: This is sample error message
07-07-2015 16:12:01 ERROR[TestDriver]: This is sample error message
07-07-2015 16:12:10 ERROR[TestDriver]: This is sample error message
07-07-2015 16:12:10 ERROR[TestDriver]: This is sample error message
07-07-2015 16:14:17 ERROR[TestDriver]: This is sample error message
07-07-2015 16:14:26 ERROR[TestDriver]: This is sample error message
07-07-2015 16:14:26 ERROR[TestDriver]: This is sample error message
07-07-2015 16:18:22 ERROR[TestDriver]: This is sample error message
07-07-2015 16:18:28 ERROR[TestDriver]: This is sample error message
07-07-2015 16:18:28 ERROR[TestDriver]: This is sample error message
07-07-2015 16:19:14 ERROR[TestDriver]: This is sample error message
07-07-2015 16:19:22 ERROR[TestDriver]: This is sample error message
07-07-2015 16:19:22 ERROR[TestDriver]: This is sample error message
07-07-2015 16:22:40 ERROR[TestDriver]: This is sample error message
07-07-2015 16:22:48 ERROR[TestDriver]: This is sample error message
07-07-2015 16:22:48 ERROR[TestDriver]: This is sample error message
07-07-2015 16:31:04 ERROR[TestDriver]: This is sample error message
07-07-2015 16:31:13 ERROR[TestDriver]: This is sample error message
07-07-2015 16:31:13 ERROR[TestDriver]: This is sample error message
07-07-2015 16:31:54 ERROR[TestDriver]: This is sample error message
07-07-2015 16:32:02 ERROR[TestDriver]: This is sample error message
07-07-2015 16:32:02 ERROR[TestDriver]: This is sample error message
07-07-2015 16:35:13 ERROR[TestDriver]: This is sample error message
07-07-2015 16:35:22 ERROR[TestDriver]: This is sample error message
07-07-2015 16:35:22 ERROR[TestDriver]: This is sample error message
07-07-2015 16:37:06 ERROR[TestDriver]: This is sample error message
07-07-2015 16:37:14 ERROR[TestDriver]: This is sample error message
07-07-2015 16:37:14 ERROR[TestDriver]: This is sample error message
07-07-2015 16:39:59 ERROR[TestDriver]: This is sample error message
07-07-2015 16:40:06 ERROR[TestDriver]: This is sample error message
07-07-2015 16:40:06 ERROR[TestDriver]: This is sample error message
07-07-2015 16:42:17 ERROR[TestDriver]: This is sample error message
07-07-2015 16:42:25 ERROR[TestDriver]: This is sample error message
07-07-2015 16:42:25 ERROR[TestDriver]: This is sample error message
07-07-2015 16:46:00 ERROR[TestDriver]: This is sample error message
07-07-2015 16:46:09 ERROR[TestDriver]: This is sample error message
07-07-2015 16:46:09 ERROR[TestDriver]: This is sample error message
07-07-2015 16:46:39 ERROR[TestDriver]: This is sample error message
07-07-2015 16:46:48 ERROR[TestDriver]: This is sample error message
07-07-2015 16:46:48 ERROR[TestDriver]: This is sample error message
07-07-2015 16:49:14 ERROR[TestDriver]: This is sample error message
07-07-2015 16:49:23 ERROR[TestDriver]: This is sample error message
07-07-2015 16:49:23 ERROR[TestDriver]: This is sample error message
07-07-2015 16:50:31 ERROR[TestDriver]: This is sample error message
07-07-2015 16:50:39 ERROR[TestDriver]: This is sample error message
07-07-2015 16:50:39 ERROR[TestDriver]: This is sample error message
07-07-2015 16:52:25 ERROR[TestDriver]: This is sample error message
07-07-2015 16:52:34 ERROR[TestDriver]: This is sample error message
07-07-2015 16:52:34 ERROR[TestDriver]: This is sample error message
07-07-2015 16:53:14 ERROR[TestDriver]: This is sample error message
07-07-2015 16:53:22 ERROR[TestDriver]: This is sample error message
07-07-2015 16:53:22 ERROR[TestDriver]: This is sample error message
07-07-2015 16:53:50 ERROR[TestDriver]: This is sample error message
07-07-2015 16:53:58 ERROR[TestDriver]: This is sample error message
07-07-2015 16:53:58 ERROR[TestDriver]: This is sample error message
07-07-2015 16:54:54 ERROR[TestDriver]: This is sample error message
07-07-2015 16:55:02 ERROR[TestDriver]: This is sample error message
07-07-2015 16:55:02 ERROR[TestDriver]: This is sample error message
07-07-2015 17:13:42 ERROR[TestDriver]: This is sample error message
07-07-2015 17:13:51 ERROR[TestDriver]: This is sample error message
07-07-2015 17:13:51 ERROR[TestDriver]: This is sample error message
07-07-2015 17:15:31 ERROR[TestDriver]: This is sample error message
07-07-2015 17:15:39 ERROR[TestDriver]: This is sample error message
07-07-2015 17:15:39 ERROR[TestDriver]: This is sample error message
07-07-2015 17:18:17 ERROR[TestDriver]: This is sample error message
07-07-2015 17:18:26 ERROR[TestDriver]: This is sample error message
07-07-2015 17:18:26 ERROR[TestDriver]: This is sample error message
07-07-2015 17:21:21 ERROR[TestDriver]: This is sample error message
07-07-2015 17:21:29 ERROR[TestDriver]: This is sample error message
07-07-2015 17:21:29 ERROR[TestDriver]: This is sample error message
07-07-2015 17:22:39 ERROR[TestDriver]: This is sample error message
07-07-2015 17:22:48 ERROR[TestDriver]: This is sample error message
07-07-2015 17:22:48 ERROR[TestDriver]: This is sample error message
07-07-2015 17:27:13 ERROR[TestDriver]: This is sample error message
07-07-2015 17:27:21 ERROR[TestDriver]: This is sample error message
07-07-2015 17:27:21 ERROR[TestDriver]: This is sample error message
07-07-2015 17:28:02 ERROR[TestDriver]: This is sample error message
07-07-2015 17:28:11 ERROR[TestDriver]: This is sample error message
07-07-2015 17:28:11 ERROR[TestDriver]: This is sample error message
07-07-2015 17:29:22 ERROR[TestDriver]: This is sample error message
07-07-2015 17:29:30 ERROR[TestDriver]: This is sample error message
07-07-2015 17:29:30 ERROR[TestDriver]: This is sample error message
